language: go

go:
  - 1.8.x

sudo: required

addons:
  firefox: latest
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java8-set-default

install:
  - testing/setup.sh

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - go get ./...

script:
  - go test